version: "3.8"
services:
    db:
        image: mysql
        container_name: database
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks:
            - cloudbird

    # Symfony apache project container
    www:
        build: docker/php
        container_name: symfony
        ports:
            - "80:80"
        volumes:
            - ./docker/php/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www
        restart: always
        networks:
            - cloudbird

networks:
    cloudbird:

volumes:
    db-data:
